version: "3.8"
name: boardly

services:
  database:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - database-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    ports:
      - "${MINIO_PORT}:${MINIO_PORT}"
      - "${MINIO_UI_PORT}:${MINIO_UI_PORT}"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":${MINIO_UI_PORT}"
    volumes:
      - minio-data:/data

  socket:
    build:
      context: ./websocket
    ports:
      - "${WEBSOCKET_PORT}:${WEBSOCKET_PORT}"
    environment:
      - PORT=${WEBSOCKET_PORT}
      - FRONTEND_URL=${FRONTEND_URL}

volumes:
  database-data:
  minio-data:
